site_name: cloud-projeto-1
nav:
  - Projeto - parte 1:
    - Home: index.md
    - Prints da API: testes.md
    - Vídeo do funcionamento: video.md
  - Projeto - parte 2:
    - Home: index2.md
    - Breve explicação: explicacao.md
    - Vídeo do funcionamento - AWS: video2.md
    - app-deployment.yaml : app-deployment.md
    - postgres-deployment.yaml : postgres-deployment.md
theme:
  name: material